# Generated by Django 4.1.7 on 2023-03-09 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0003_produto_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.TextField()),
                ('disco_pedido', models.IntegerField()),
                ('total_geral', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('quantidade', models.IntegerField()),
                ('valor', models.FloatField()),
                ('total', models.FloatField()),
                ('pedido_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafeteria.pedidocliente')),
            ],
        ),
    ]
