# Generated by Django 4.1.7 on 2023-03-12 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0004_pedidocliente_pedidos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidocliente',
            old_name='total_geral',
            new_name='total_geral3',
        ),
    ]
