# Generated by Django 4.1.7 on 2023-03-12 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0005_rename_total_geral_pedidocliente_total_geral3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidocliente',
            old_name='total_geral3',
            new_name='total_geral',
        ),
    ]
