# Generated by Django 4.1.7 on 2023-03-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0006_rename_total_geral3_pedidocliente_total_geral'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocliente',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
