# Generated by Django 4.1.7 on 2023-03-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0008_alter_pedidocliente_finalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocliente',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
